[colors.primary]
background = "#212337"
foreground = "#c8d3f5"

[colors.normal]
black = "#161a2a"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#c8d3f5"

[colors.bright]
black = "#444a73"
red = "#ff98a4"
green = "#77e0c6"
yellow = "#ffcc99"
blue = "#50c4fa"
magenta = "#baacff"
cyan = "#b4f9f8"
white = "#ffffff"